apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialize-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shantiswarup/socialize.git
    targetRevision: HEAD
    path: deployments/socialize-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: socialize
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
